name: Deploy
on:
  push:
    branches:
      - main
#   pull_request:
#     branches:
#       - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
     permissions:
       id-token:ddp_wbZYeZ3MxvfJdZHeYHtqr4HPCqg1jZ111wh8 # Needed for auth with Deno Deploy
       contents: read # Needed to clone the repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm i --legacy-peer-deps

      - name: Run build
        run: npm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
            project: "desp-astro-qr-generator"
            entrypoint: "./dist/server/entry.mjs"
