name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v0.1.8
        with:
            bun-version: latest

      - name: Bun version
        run: |
          bun --version

      - name: PATH
        run: echo $PATH

      - name: Install modules
        run: bun install

      - name: Run build
        run: bun run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
            project: "desp-astro-qr-generator"
            entrypoint: "./dist/server/entry.mjs"
