name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v0.1.8
        with:
            bun-version: latest

      - name: Install modules
        run: bun install

      - name: Run build
        run: bun run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
            project: "desp-qr-generator"
            entrypoint: https://deno.land/std@0.177.0/http/file_server.ts
            root: dist/server/entry.mjs
