name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
            bun-version: "0.5.5"
      - name: Install modules
        run: bun install
      - name: Run eslint
        run: bun run lint:eslint
      - name: Run build
        run: bun run build
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
            project: "desp-qr-generator"
            entrypoint: server/entry.mjs
            root: dist
